[package]
name = "parallel-seismic-response"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { version = "1.10.0", optional = true }
seismic-response = "0.4.0"

[profile.release]
lto = true

[features]
rayon = ["dep:rayon"]
